/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\avatar.glb -o src\Avatar.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/avatar.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.001, 0]}>
        <mesh geometry={nodes.Earring001.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Earring004.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Ears001.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Ears003.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Eyebrow003.geometry} material={materials['Hair.004']} />
        <mesh geometry={nodes.Eyebrow1003.geometry} material={materials['Hair.006']} />
        <mesh geometry={nodes.Hair003.geometry} material={materials['Hair.004']} />
        <mesh geometry={nodes.Head003.geometry} material={materials['Skin.002']} />
        <mesh geometry={nodes.Left_Down_eye_lid001.geometry} material={materials['Eye Lid']} />
        <mesh geometry={nodes.Left_Up_eye_lid001.geometry} material={materials['Eye Lid']} />
        <mesh geometry={nodes.Moustach003.geometry} material={materials['Hair.004']} />
        <mesh geometry={nodes.Right_Down_eye_lid.geometry} material={materials['Eye Lid']} />
        <mesh geometry={nodes.Right_Up_eye_lid.geometry} material={materials['Eye Lid']} />
        <mesh geometry={nodes.Sphere001.geometry} material={materials['Eye Ball.002']} />
        <mesh geometry={nodes.Sphere001_1.geometry} material={materials['Pupil.002']} />
        <mesh geometry={nodes.Sphere001_2.geometry} material={materials.Material} />
        <mesh geometry={nodes.Sphere007.geometry} material={materials['Eye Ball.002']} />
        <mesh geometry={nodes.Sphere007_1.geometry} material={materials['Pupil.002']} />
        <mesh geometry={nodes.Sphere007_2.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.Body.geometry} material={materials.material} position={[-0.004, 0.016, 0]} rotation={[0, 0, -0.01]} />
      <mesh geometry={nodes.Mesh_0.geometry} material={materials.Material_0} position={[-0.002, 0.578, 0.01]} rotation={[-3.131, 0.001, 0.001]} scale={-0.61} />
      <primitive object={nodes.spine} />
    </group>
  )
}

useGLTF.preload('/avatar.glb')
